FROM python:3.7.3-slim

WORKDIR /app
COPY requirements.txt /app/requirements.txt

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . /app
EXPOSE 5000
CMD gunicorn -w 1 -b 0.0.0.0:5000 app:app