version: '3.7'

services:

  web:
    image: saintsin/test-swarm_web:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    env_file:
      - server.env
    depends_on:
      - redis
    networks:
      - app

  worker:
    image: saintsin/test-swarm_worker:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    env_file:
      - server.env
    depends_on:
      - redis
    networks:
      - app

  redis:
    image: "redis:5.0.9"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    networks:
      - app

  nginx:
    image: saintsin/test-swarm_nginx:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - app

  visualizer:
    image: dockersamples/visualizer:latest
    ports:
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - app

networks:
  app:
    driver: overlay

volumes:
  data-volume:
    driver: local